

target 'iWatchIt' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_modular_headers!

  # Pods for iWatchIt
  pod 'Firebase/Core'
  pod 'FirebaseCrashlytics'
  pod 'FirebaseAnalytics'
  pod 'Firebase/DynamicLinks'
  pod 'Firebase/Database'
  pod 'Google-Mobile-Ads-SDK'
  target 'iWatchItTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iWatchItUITests' do
    # Pods for testing
  end

end
